"""Explicit PySpark StructType schema contracts for all 8 Home Credit tables.

Empirically derived and frozen during Phase 1 profiling.
DO NOT use inferSchema=True in downstream ingestion phases.
"""

from pyspark.sql.types import (
    BooleanType,
    ByteType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    ShortType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

APPLICATION_TRAIN_SCHEMA = StructType([
    StructField("SK_ID_CURR", IntegerType(), True),
    StructField("TARGET", IntegerType(), True),
    StructField("NAME_CONTRACT_TYPE", StringType(), True),
    StructField("CODE_GENDER", StringType(), True),
    StructField("FLAG_OWN_CAR", StringType(), True),
    StructField("FLAG_OWN_REALTY", StringType(), True),
    StructField("CNT_CHILDREN", IntegerType(), True),
    StructField("AMT_INCOME_TOTAL", DoubleType(), True),
    StructField("AMT_CREDIT", DoubleType(), True),
    StructField("AMT_ANNUITY", DoubleType(), True),
    StructField("AMT_GOODS_PRICE", DoubleType(), True),
    StructField("NAME_TYPE_SUITE", StringType(), True),
    StructField("NAME_INCOME_TYPE", StringType(), True),
    StructField("NAME_EDUCATION_TYPE", StringType(), True),
    StructField("NAME_FAMILY_STATUS", StringType(), True),
    StructField("NAME_HOUSING_TYPE", StringType(), True),
    StructField("REGION_POPULATION_RELATIVE", DoubleType(), True),
    StructField("DAYS_BIRTH", IntegerType(), True),
    StructField("DAYS_EMPLOYED", IntegerType(), True),
    StructField("DAYS_REGISTRATION", DoubleType(), True),
    StructField("DAYS_ID_PUBLISH", IntegerType(), True),
    StructField("OWN_CAR_AGE", DoubleType(), True),
    StructField("FLAG_MOBIL", IntegerType(), True),
    StructField("FLAG_EMP_PHONE", IntegerType(), True),
    StructField("FLAG_WORK_PHONE", IntegerType(), True),
    StructField("FLAG_CONT_MOBILE", IntegerType(), True),
    StructField("FLAG_PHONE", IntegerType(), True),
    StructField("FLAG_EMAIL", IntegerType(), True),
    StructField("OCCUPATION_TYPE", StringType(), True),
    StructField("CNT_FAM_MEMBERS", DoubleType(), True),
    StructField("REGION_RATING_CLIENT", IntegerType(), True),
    StructField("REGION_RATING_CLIENT_W_CITY", IntegerType(), True),
    StructField("WEEKDAY_APPR_PROCESS_START", StringType(), True),
    StructField("HOUR_APPR_PROCESS_START", IntegerType(), True),
    StructField("REG_REGION_NOT_LIVE_REGION", IntegerType(), True),
    StructField("REG_REGION_NOT_WORK_REGION", IntegerType(), True),
    StructField("LIVE_REGION_NOT_WORK_REGION", IntegerType(), True),
    StructField("REG_CITY_NOT_LIVE_CITY", IntegerType(), True),
    StructField("REG_CITY_NOT_WORK_CITY", IntegerType(), True),
    StructField("LIVE_CITY_NOT_WORK_CITY", IntegerType(), True),
    StructField("ORGANIZATION_TYPE", StringType(), True),
    StructField("EXT_SOURCE_1", DoubleType(), True),
    StructField("EXT_SOURCE_2", DoubleType(), True),
    StructField("EXT_SOURCE_3", DoubleType(), True),
    StructField("APARTMENTS_AVG", DoubleType(), True),
    StructField("BASEMENTAREA_AVG", DoubleType(), True),
    StructField("YEARS_BEGINEXPLUATATION_AVG", DoubleType(), True),
    StructField("YEARS_BUILD_AVG", DoubleType(), True),
    StructField("COMMONAREA_AVG", DoubleType(), True),
    StructField("ELEVATORS_AVG", DoubleType(), True),
    StructField("ENTRANCES_AVG", DoubleType(), True),
    StructField("FLOORSMAX_AVG", DoubleType(), True),
    StructField("FLOORSMIN_AVG", DoubleType(), True),
    StructField("LANDAREA_AVG", DoubleType(), True),
    StructField("LIVINGAPARTMENTS_AVG", DoubleType(), True),
    StructField("LIVINGAREA_AVG", DoubleType(), True),
    StructField("NONLIVINGAPARTMENTS_AVG", DoubleType(), True),
    StructField("NONLIVINGAREA_AVG", DoubleType(), True),
    StructField("APARTMENTS_MODE", DoubleType(), True),
    StructField("BASEMENTAREA_MODE", DoubleType(), True),
    StructField("YEARS_BEGINEXPLUATATION_MODE", DoubleType(), True),
    StructField("YEARS_BUILD_MODE", DoubleType(), True),
    StructField("COMMONAREA_MODE", DoubleType(), True),
    StructField("ELEVATORS_MODE", DoubleType(), True),
    StructField("ENTRANCES_MODE", DoubleType(), True),
    StructField("FLOORSMAX_MODE", DoubleType(), True),
    StructField("FLOORSMIN_MODE", DoubleType(), True),
    StructField("LANDAREA_MODE", DoubleType(), True),
    StructField("LIVINGAPARTMENTS_MODE", DoubleType(), True),
    StructField("LIVINGAREA_MODE", DoubleType(), True),
    StructField("NONLIVINGAPARTMENTS_MODE", DoubleType(), True),
    StructField("NONLIVINGAREA_MODE", DoubleType(), True),
    StructField("APARTMENTS_MEDI", DoubleType(), True),
    StructField("BASEMENTAREA_MEDI", DoubleType(), True),
    StructField("YEARS_BEGINEXPLUATATION_MEDI", DoubleType(), True),
    StructField("YEARS_BUILD_MEDI", DoubleType(), True),
    StructField("COMMONAREA_MEDI", DoubleType(), True),
    StructField("ELEVATORS_MEDI", DoubleType(), True),
    StructField("ENTRANCES_MEDI", DoubleType(), True),
    StructField("FLOORSMAX_MEDI", DoubleType(), True),
    StructField("FLOORSMIN_MEDI", DoubleType(), True),
    StructField("LANDAREA_MEDI", DoubleType(), True),
    StructField("LIVINGAPARTMENTS_MEDI", DoubleType(), True),
    StructField("LIVINGAREA_MEDI", DoubleType(), True),
    StructField("NONLIVINGAPARTMENTS_MEDI", DoubleType(), True),
    StructField("NONLIVINGAREA_MEDI", DoubleType(), True),
    StructField("FONDKAPREMONT_MODE", StringType(), True),
    StructField("HOUSETYPE_MODE", StringType(), True),
    StructField("TOTALAREA_MODE", DoubleType(), True),
    StructField("WALLSMATERIAL_MODE", StringType(), True),
    StructField("EMERGENCYSTATE_MODE", StringType(), True),
    StructField("OBS_30_CNT_SOCIAL_CIRCLE", DoubleType(), True),
    StructField("DEF_30_CNT_SOCIAL_CIRCLE", DoubleType(), True),
    StructField("OBS_60_CNT_SOCIAL_CIRCLE", DoubleType(), True),
    StructField("DEF_60_CNT_SOCIAL_CIRCLE", DoubleType(), True),
    StructField("DAYS_LAST_PHONE_CHANGE", DoubleType(), True),
    StructField("FLAG_DOCUMENT_2", IntegerType(), True),
    StructField("FLAG_DOCUMENT_3", IntegerType(), True),
    StructField("FLAG_DOCUMENT_4", IntegerType(), True),
    StructField("FLAG_DOCUMENT_5", IntegerType(), True),
    StructField("FLAG_DOCUMENT_6", IntegerType(), True),
    StructField("FLAG_DOCUMENT_7", IntegerType(), True),
    StructField("FLAG_DOCUMENT_8", IntegerType(), True),
    StructField("FLAG_DOCUMENT_9", IntegerType(), True),
    StructField("FLAG_DOCUMENT_10", IntegerType(), True),
    StructField("FLAG_DOCUMENT_11", IntegerType(), True),
    StructField("FLAG_DOCUMENT_12", IntegerType(), True),
    StructField("FLAG_DOCUMENT_13", IntegerType(), True),
    StructField("FLAG_DOCUMENT_14", IntegerType(), True),
    StructField("FLAG_DOCUMENT_15", IntegerType(), True),
    StructField("FLAG_DOCUMENT_16", IntegerType(), True),
    StructField("FLAG_DOCUMENT_17", IntegerType(), True),
    StructField("FLAG_DOCUMENT_18", IntegerType(), True),
    StructField("FLAG_DOCUMENT_19", IntegerType(), True),
    StructField("FLAG_DOCUMENT_20", IntegerType(), True),
    StructField("FLAG_DOCUMENT_21", IntegerType(), True),
    StructField("AMT_REQ_CREDIT_BUREAU_HOUR", DoubleType(), True),
    StructField("AMT_REQ_CREDIT_BUREAU_DAY", DoubleType(), True),
    StructField("AMT_REQ_CREDIT_BUREAU_WEEK", DoubleType(), True),
    StructField("AMT_REQ_CREDIT_BUREAU_MON", DoubleType(), True),
    StructField("AMT_REQ_CREDIT_BUREAU_QRT", DoubleType(), True),
    StructField("AMT_REQ_CREDIT_BUREAU_YEAR", DoubleType(), True),
])

APPLICATION_TEST_SCHEMA = StructType([
    StructField("SK_ID_CURR", IntegerType(), True),
    StructField("NAME_CONTRACT_TYPE", StringType(), True),
    StructField("CODE_GENDER", StringType(), True),
    StructField("FLAG_OWN_CAR", StringType(), True),
    StructField("FLAG_OWN_REALTY", StringType(), True),
    StructField("CNT_CHILDREN", IntegerType(), True),
    StructField("AMT_INCOME_TOTAL", DoubleType(), True),
    StructField("AMT_CREDIT", DoubleType(), True),
    StructField("AMT_ANNUITY", DoubleType(), True),
    StructField("AMT_GOODS_PRICE", DoubleType(), True),
    StructField("NAME_TYPE_SUITE", StringType(), True),
    StructField("NAME_INCOME_TYPE", StringType(), True),
    StructField("NAME_EDUCATION_TYPE", StringType(), True),
    StructField("NAME_FAMILY_STATUS", StringType(), True),
    StructField("NAME_HOUSING_TYPE", StringType(), True),
    StructField("REGION_POPULATION_RELATIVE", DoubleType(), True),
    StructField("DAYS_BIRTH", IntegerType(), True),
    StructField("DAYS_EMPLOYED", IntegerType(), True),
    StructField("DAYS_REGISTRATION", DoubleType(), True),
    StructField("DAYS_ID_PUBLISH", IntegerType(), True),
    StructField("OWN_CAR_AGE", DoubleType(), True),
    StructField("FLAG_MOBIL", IntegerType(), True),
    StructField("FLAG_EMP_PHONE", IntegerType(), True),
    StructField("FLAG_WORK_PHONE", IntegerType(), True),
    StructField("FLAG_CONT_MOBILE", IntegerType(), True),
    StructField("FLAG_PHONE", IntegerType(), True),
    StructField("FLAG_EMAIL", IntegerType(), True),
    StructField("OCCUPATION_TYPE", StringType(), True),
    StructField("CNT_FAM_MEMBERS", DoubleType(), True),
    StructField("REGION_RATING_CLIENT", IntegerType(), True),
    StructField("REGION_RATING_CLIENT_W_CITY", IntegerType(), True),
    StructField("WEEKDAY_APPR_PROCESS_START", StringType(), True),
    StructField("HOUR_APPR_PROCESS_START", IntegerType(), True),
    StructField("REG_REGION_NOT_LIVE_REGION", IntegerType(), True),
    StructField("REG_REGION_NOT_WORK_REGION", IntegerType(), True),
    StructField("LIVE_REGION_NOT_WORK_REGION", IntegerType(), True),
    StructField("REG_CITY_NOT_LIVE_CITY", IntegerType(), True),
    StructField("REG_CITY_NOT_WORK_CITY", IntegerType(), True),
    StructField("LIVE_CITY_NOT_WORK_CITY", IntegerType(), True),
    StructField("ORGANIZATION_TYPE", StringType(), True),
    StructField("EXT_SOURCE_1", DoubleType(), True),
    StructField("EXT_SOURCE_2", DoubleType(), True),
    StructField("EXT_SOURCE_3", DoubleType(), True),
    StructField("APARTMENTS_AVG", DoubleType(), True),
    StructField("BASEMENTAREA_AVG", DoubleType(), True),
    StructField("YEARS_BEGINEXPLUATATION_AVG", DoubleType(), True),
    StructField("YEARS_BUILD_AVG", DoubleType(), True),
    StructField("COMMONAREA_AVG", DoubleType(), True),
    StructField("ELEVATORS_AVG", DoubleType(), True),
    StructField("ENTRANCES_AVG", DoubleType(), True),
    StructField("FLOORSMAX_AVG", DoubleType(), True),
    StructField("FLOORSMIN_AVG", DoubleType(), True),
    StructField("LANDAREA_AVG", DoubleType(), True),
    StructField("LIVINGAPARTMENTS_AVG", DoubleType(), True),
    StructField("LIVINGAREA_AVG", DoubleType(), True),
    StructField("NONLIVINGAPARTMENTS_AVG", DoubleType(), True),
    StructField("NONLIVINGAREA_AVG", DoubleType(), True),
    StructField("APARTMENTS_MODE", DoubleType(), True),
    StructField("BASEMENTAREA_MODE", DoubleType(), True),
    StructField("YEARS_BEGINEXPLUATATION_MODE", DoubleType(), True),
    StructField("YEARS_BUILD_MODE", DoubleType(), True),
    StructField("COMMONAREA_MODE", DoubleType(), True),
    StructField("ELEVATORS_MODE", DoubleType(), True),
    StructField("ENTRANCES_MODE", DoubleType(), True),
    StructField("FLOORSMAX_MODE", DoubleType(), True),
    StructField("FLOORSMIN_MODE", DoubleType(), True),
    StructField("LANDAREA_MODE", DoubleType(), True),
    StructField("LIVINGAPARTMENTS_MODE", DoubleType(), True),
    StructField("LIVINGAREA_MODE", DoubleType(), True),
    StructField("NONLIVINGAPARTMENTS_MODE", DoubleType(), True),
    StructField("NONLIVINGAREA_MODE", DoubleType(), True),
    StructField("APARTMENTS_MEDI", DoubleType(), True),
    StructField("BASEMENTAREA_MEDI", DoubleType(), True),
    StructField("YEARS_BEGINEXPLUATATION_MEDI", DoubleType(), True),
    StructField("YEARS_BUILD_MEDI", DoubleType(), True),
    StructField("COMMONAREA_MEDI", DoubleType(), True),
    StructField("ELEVATORS_MEDI", DoubleType(), True),
    StructField("ENTRANCES_MEDI", DoubleType(), True),
    StructField("FLOORSMAX_MEDI", DoubleType(), True),
    StructField("FLOORSMIN_MEDI", DoubleType(), True),
    StructField("LANDAREA_MEDI", DoubleType(), True),
    StructField("LIVINGAPARTMENTS_MEDI", DoubleType(), True),
    StructField("LIVINGAREA_MEDI", DoubleType(), True),
    StructField("NONLIVINGAPARTMENTS_MEDI", DoubleType(), True),
    StructField("NONLIVINGAREA_MEDI", DoubleType(), True),
    StructField("FONDKAPREMONT_MODE", StringType(), True),
    StructField("HOUSETYPE_MODE", StringType(), True),
    StructField("TOTALAREA_MODE", DoubleType(), True),
    StructField("WALLSMATERIAL_MODE", StringType(), True),
    StructField("EMERGENCYSTATE_MODE", StringType(), True),
    StructField("OBS_30_CNT_SOCIAL_CIRCLE", DoubleType(), True),
    StructField("DEF_30_CNT_SOCIAL_CIRCLE", DoubleType(), True),
    StructField("OBS_60_CNT_SOCIAL_CIRCLE", DoubleType(), True),
    StructField("DEF_60_CNT_SOCIAL_CIRCLE", DoubleType(), True),
    StructField("DAYS_LAST_PHONE_CHANGE", DoubleType(), True),
    StructField("FLAG_DOCUMENT_2", IntegerType(), True),
    StructField("FLAG_DOCUMENT_3", IntegerType(), True),
    StructField("FLAG_DOCUMENT_4", IntegerType(), True),
    StructField("FLAG_DOCUMENT_5", IntegerType(), True),
    StructField("FLAG_DOCUMENT_6", IntegerType(), True),
    StructField("FLAG_DOCUMENT_7", IntegerType(), True),
    StructField("FLAG_DOCUMENT_8", IntegerType(), True),
    StructField("FLAG_DOCUMENT_9", IntegerType(), True),
    StructField("FLAG_DOCUMENT_10", IntegerType(), True),
    StructField("FLAG_DOCUMENT_11", IntegerType(), True),
    StructField("FLAG_DOCUMENT_12", IntegerType(), True),
    StructField("FLAG_DOCUMENT_13", IntegerType(), True),
    StructField("FLAG_DOCUMENT_14", IntegerType(), True),
    StructField("FLAG_DOCUMENT_15", IntegerType(), True),
    StructField("FLAG_DOCUMENT_16", IntegerType(), True),
    StructField("FLAG_DOCUMENT_17", IntegerType(), True),
    StructField("FLAG_DOCUMENT_18", IntegerType(), True),
    StructField("FLAG_DOCUMENT_19", IntegerType(), True),
    StructField("FLAG_DOCUMENT_20", IntegerType(), True),
    StructField("FLAG_DOCUMENT_21", IntegerType(), True),
    StructField("AMT_REQ_CREDIT_BUREAU_HOUR", DoubleType(), True),
    StructField("AMT_REQ_CREDIT_BUREAU_DAY", DoubleType(), True),
    StructField("AMT_REQ_CREDIT_BUREAU_WEEK", DoubleType(), True),
    StructField("AMT_REQ_CREDIT_BUREAU_MON", DoubleType(), True),
    StructField("AMT_REQ_CREDIT_BUREAU_QRT", DoubleType(), True),
    StructField("AMT_REQ_CREDIT_BUREAU_YEAR", DoubleType(), True),
])

BUREAU_SCHEMA = StructType([
    StructField("SK_ID_CURR", IntegerType(), True),
    StructField("SK_ID_BUREAU", IntegerType(), True),
    StructField("CREDIT_ACTIVE", StringType(), True),
    StructField("CREDIT_CURRENCY", StringType(), True),
    StructField("DAYS_CREDIT", IntegerType(), True),
    StructField("CREDIT_DAY_OVERDUE", IntegerType(), True),
    StructField("DAYS_CREDIT_ENDDATE", DoubleType(), True),
    StructField("DAYS_ENDDATE_FACT", DoubleType(), True),
    StructField("AMT_CREDIT_MAX_OVERDUE", DoubleType(), True),
    StructField("CNT_CREDIT_PROLONG", IntegerType(), True),
    StructField("AMT_CREDIT_SUM", DoubleType(), True),
    StructField("AMT_CREDIT_SUM_DEBT", DoubleType(), True),
    StructField("AMT_CREDIT_SUM_LIMIT", DoubleType(), True),
    StructField("AMT_CREDIT_SUM_OVERDUE", DoubleType(), True),
    StructField("CREDIT_TYPE", StringType(), True),
    StructField("DAYS_CREDIT_UPDATE", IntegerType(), True),
    StructField("AMT_ANNUITY", DoubleType(), True),
])

BUREAU_BALANCE_SCHEMA = StructType([
    StructField("SK_ID_BUREAU", IntegerType(), True),
    StructField("MONTHS_BALANCE", IntegerType(), True),
    StructField("STATUS", StringType(), True),
])

PREVIOUS_APPLICATION_SCHEMA = StructType([
    StructField("SK_ID_PREV", IntegerType(), True),
    StructField("SK_ID_CURR", IntegerType(), True),
    StructField("NAME_CONTRACT_TYPE", StringType(), True),
    StructField("AMT_ANNUITY", DoubleType(), True),
    StructField("AMT_APPLICATION", DoubleType(), True),
    StructField("AMT_CREDIT", DoubleType(), True),
    StructField("AMT_DOWN_PAYMENT", DoubleType(), True),
    StructField("AMT_GOODS_PRICE", DoubleType(), True),
    StructField("WEEKDAY_APPR_PROCESS_START", StringType(), True),
    StructField("HOUR_APPR_PROCESS_START", IntegerType(), True),
    StructField("FLAG_LAST_APPL_PER_CONTRACT", StringType(), True),
    StructField("NFLAG_LAST_APPL_IN_DAY", IntegerType(), True),
    StructField("RATE_DOWN_PAYMENT", DoubleType(), True),
    StructField("RATE_INTEREST_PRIMARY", DoubleType(), True),
    StructField("RATE_INTEREST_PRIVILEGED", DoubleType(), True),
    StructField("NAME_CASH_LOAN_PURPOSE", StringType(), True),
    StructField("NAME_CONTRACT_STATUS", StringType(), True),
    StructField("DAYS_DECISION", IntegerType(), True),
    StructField("NAME_PAYMENT_TYPE", StringType(), True),
    StructField("CODE_REJECT_REASON", StringType(), True),
    StructField("NAME_TYPE_SUITE", StringType(), True),
    StructField("NAME_CLIENT_TYPE", StringType(), True),
    StructField("NAME_GOODS_CATEGORY", StringType(), True),
    StructField("NAME_PORTFOLIO", StringType(), True),
    StructField("NAME_PRODUCT_TYPE", StringType(), True),
    StructField("CHANNEL_TYPE", StringType(), True),
    StructField("SELLERPLACE_AREA", IntegerType(), True),
    StructField("NAME_SELLER_INDUSTRY", StringType(), True),
    StructField("CNT_PAYMENT", DoubleType(), True),
    StructField("NAME_YIELD_GROUP", StringType(), True),
    StructField("PRODUCT_COMBINATION", StringType(), True),
    StructField("DAYS_FIRST_DRAWING", DoubleType(), True),
    StructField("DAYS_FIRST_DUE", DoubleType(), True),
    StructField("DAYS_LAST_DUE_1ST_VERSION", DoubleType(), True),
    StructField("DAYS_LAST_DUE", DoubleType(), True),
    StructField("DAYS_TERMINATION", DoubleType(), True),
    StructField("NFLAG_INSURED_ON_APPROVAL", DoubleType(), True),
])

INSTALLMENTS_PAYMENTS_SCHEMA = StructType([
    StructField("SK_ID_PREV", IntegerType(), True),
    StructField("SK_ID_CURR", IntegerType(), True),
    StructField("NUM_INSTALMENT_VERSION", DoubleType(), True),
    StructField("NUM_INSTALMENT_NUMBER", IntegerType(), True),
    StructField("DAYS_INSTALMENT", DoubleType(), True),
    StructField("DAYS_ENTRY_PAYMENT", DoubleType(), True),
    StructField("AMT_INSTALMENT", DoubleType(), True),
    StructField("AMT_PAYMENT", DoubleType(), True),
])

CREDIT_CARD_BALANCE_SCHEMA = StructType([
    StructField("SK_ID_PREV", IntegerType(), True),
    StructField("SK_ID_CURR", IntegerType(), True),
    StructField("MONTHS_BALANCE", IntegerType(), True),
    StructField("AMT_BALANCE", DoubleType(), True),
    StructField("AMT_CREDIT_LIMIT_ACTUAL", IntegerType(), True),
    StructField("AMT_DRAWINGS_ATM_CURRENT", DoubleType(), True),
    StructField("AMT_DRAWINGS_CURRENT", DoubleType(), True),
    StructField("AMT_DRAWINGS_OTHER_CURRENT", DoubleType(), True),
    StructField("AMT_DRAWINGS_POS_CURRENT", DoubleType(), True),
    StructField("AMT_INST_MIN_REGULARITY", DoubleType(), True),
    StructField("AMT_PAYMENT_CURRENT", DoubleType(), True),
    StructField("AMT_PAYMENT_TOTAL_CURRENT", DoubleType(), True),
    StructField("AMT_RECEIVABLE_PRINCIPAL", DoubleType(), True),
    StructField("AMT_RECIVABLE", DoubleType(), True),
    StructField("AMT_TOTAL_RECEIVABLE", DoubleType(), True),
    StructField("CNT_DRAWINGS_ATM_CURRENT", DoubleType(), True),
    StructField("CNT_DRAWINGS_CURRENT", IntegerType(), True),
    StructField("CNT_DRAWINGS_OTHER_CURRENT", DoubleType(), True),
    StructField("CNT_DRAWINGS_POS_CURRENT", DoubleType(), True),
    StructField("CNT_INSTALMENT_MATURE_CUM", DoubleType(), True),
    StructField("NAME_CONTRACT_STATUS", StringType(), True),
    StructField("SK_DPD", IntegerType(), True),
    StructField("SK_DPD_DEF", IntegerType(), True),
])

POS_CASH_BALANCE_SCHEMA = StructType([
    StructField("SK_ID_PREV", IntegerType(), True),
    StructField("SK_ID_CURR", IntegerType(), True),
    StructField("MONTHS_BALANCE", IntegerType(), True),
    StructField("CNT_INSTALMENT", DoubleType(), True),
    StructField("CNT_INSTALMENT_FUTURE", DoubleType(), True),
    StructField("NAME_CONTRACT_STATUS", StringType(), True),
    StructField("SK_DPD", IntegerType(), True),
    StructField("SK_DPD_DEF", IntegerType(), True),
])

TABLE_SCHEMAS: dict[str, StructType] = {
    "application_train": APPLICATION_TRAIN_SCHEMA,
    "application_test": APPLICATION_TEST_SCHEMA,
    "bureau": BUREAU_SCHEMA,
    "bureau_balance": BUREAU_BALANCE_SCHEMA,
    "previous_application": PREVIOUS_APPLICATION_SCHEMA,
    "installments_payments": INSTALLMENTS_PAYMENTS_SCHEMA,
    "credit_card_balance": CREDIT_CARD_BALANCE_SCHEMA,
    "POS_CASH_balance": POS_CASH_BALANCE_SCHEMA,
}

def validate_schema_contract() -> bool:
    """Validate that all 8 schemas exist, have valid fields, no duplicates, and valid keys."""
    expected_tables = [
        "application_train",
        "application_test",
        "bureau",
        "bureau_balance",
        "previous_application",
        "installments_payments",
        "credit_card_balance",
        "POS_CASH_balance",
    ]
    for tbl in expected_tables:
        if tbl not in TABLE_SCHEMAS:
            raise KeyError(f"Missing schema contract for table: {tbl}")
        schema = TABLE_SCHEMAS[tbl]
        if not isinstance(schema, StructType):
            raise TypeError(f"Schema for {tbl} is not a StructType")
        names = [f.name for f in schema.fields]
        if len(names) != len(set(names)):
            raise ValueError(f"Duplicate column names detected in {tbl} schema")
        if len(names) == 0:
            raise ValueError(f"Empty schema detected in {tbl}")
    return True
